import assert from 'node:assert/strict';
import test from 'node:test';
import handler from '../api/razorpay/create-addon-order';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const keys = ['RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET'] as const;
const withEnvironment = async (values: Record<string, string | undefined>, run: () => Promise<void>) => { const old = Object.fromEntries(keys.map(key => [key, process.env[key]])); Object.entries(values).forEach(([key, value]) => value === undefined ? delete process.env[key] : process.env[key] = value); try { await run(); } finally { keys.forEach(key => old[key] === undefined ? delete process.env[key] : process.env[key] = old[key]); } };

test('add-on order rejects unsupported methods', async () => { const res = response(); await handler({method: 'GET'}, res); assert.equal(res.statusCode, 405); assert.deepEqual(res.body, {error: 'Method not allowed'}); });
test('add-on order reports missing Razorpay configuration', async () => { await withEnvironment({RAZORPAY_KEY_ID: undefined, RAZORPAY_KEY_SECRET: undefined}, async () => { const res = response(); await handler({method: 'POST', body: {}}, res); assert.equal(res.statusCode, 503); }); });
test('add-on order requires tenant and owner email', async () => { await withEnvironment({RAZORPAY_KEY_ID: 'rzp_test_characterization_key', RAZORPAY_KEY_SECRET: 'test_characterization_secret'}, async () => { const res = response(); await handler({method: 'POST', body: {}}, res); assert.equal(res.statusCode, 400); assert.deepEqual(res.body, {error: 'Tenant and owner email are required.'}); }); });
test('add-on order creates the fixed-price Razorpay order through mocked HTTP', async () => { await withEnvironment({RAZORPAY_KEY_ID: 'rzp_test_characterization_key', RAZORPAY_KEY_SECRET: 'test_characterization_secret'}, async () => { const oldFetch = globalThis.fetch; let requested: any; globalThis.fetch = (async (url: any, init: any) => { requested = {url: String(url), init}; return {ok: true, text: async () => JSON.stringify({id: 'order_characterization'})}; }) as any; try { const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant-test', email: 'owner@example.test'}}, res); const outgoing = JSON.parse(requested.init.body); assert.equal(requested.url, 'https://api.razorpay.com/v1/orders'); assert.equal(requested.init.method, 'POST'); assert.equal(requested.init.headers.Authorization, `Basic ${Buffer.from('rzp_test_characterization_key:test_characterization_secret').toString('base64')}`); assert.equal(outgoing.amount, 50000); assert.equal(outgoing.currency, 'INR'); assert.deepEqual(outgoing.notes, {tenantId: 'tenant-test', ownerEmail: 'owner@example.test', purchaseType: 'additional_store'}); assert.match(outgoing.receipt, /^store_/); assert.equal(res.statusCode, 200); assert.deepEqual(res.body, {keyId: 'rzp_test_characterization_key', orderId: 'order_characterization', amount: 50000, currency: 'INR'}); } finally { globalThis.fetch = oldFetch; } }); });
test('add-on order preserves Razorpay upstream errors', async () => { await withEnvironment({RAZORPAY_KEY_ID: 'rzp_test_characterization_key', RAZORPAY_KEY_SECRET: 'test_characterization_secret'}, async () => { const oldFetch = globalThis.fetch; globalThis.fetch = (async () => ({ok: false, status: 422, text: async () => JSON.stringify({error: {description: 'Rejected test order'}})})) as any; try { const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant-test', email: 'owner@example.test'}}, res); assert.equal(res.statusCode, 422); assert.deepEqual(res.body, {error: 'Rejected test order'}); } finally { globalThis.fetch = oldFetch; } }); });
