import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import test from 'node:test';
import handler from '../api/razorpay/verify-whatsapp-wallet-payment';
import {adminStoreAdapter} from '../src/server/adapters/store';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const secret = 'test_razorpay_secret';
const signature = (order: string, payment: string) => createHmac('sha256', secret).update(`${order}|${payment}`).digest('hex');
const env = async (run: () => Promise<void>) => { const old = {secret: process.env.RAZORPAY_KEY_SECRET, key: process.env.RAZORPAY_KEY_ID}; process.env.RAZORPAY_KEY_SECRET = secret; process.env.RAZORPAY_KEY_ID = 'rzp_test_characterization_key'; try { await run(); } finally { old.secret === undefined ? delete process.env.RAZORPAY_KEY_SECRET : process.env.RAZORPAY_KEY_SECRET = old.secret; old.key === undefined ? delete process.env.RAZORPAY_KEY_ID : process.env.RAZORPAY_KEY_ID = old.key; } };

test('wallet verification rejects unsupported methods and incomplete data', async () => { const method = response(); await handler({method: 'GET'}, method); assert.equal(method.statusCode, 405); await env(async () => { const missing = response(); await handler({method: 'POST', headers: {}, body: {}}, missing); assert.equal(missing.statusCode, 400); }); });
test('wallet verification rejects invalid signatures without a wallet transaction', async () => { await env(async () => { let transactions = 0; const fakeDb: any = {doc: () => ({get: async () => ({exists: true, data: () => ({tenantId: 'owner', workspaceScope: 'owner'})})}), runTransaction: async () => { transactions += 1; }}; const oldFetch = globalThis.fetch; globalThis.fetch = (async () => ({ok: true, json: async () => ({users: [{email: 'owner@example.test'}]})})) as any; adminStoreAdapter.setDbForTests(() => fakeDb); try { const res = response(); await handler({method: 'POST', headers: {authorization: 'Bearer fake', 'x-firebase-api-key': 'fake'}, body: {workspaceScope: 'owner', razorpayOrderId: 'order-1', razorpayPaymentId: 'pay-1', razorpaySignature: 'invalid'}}, res); assert.equal(res.statusCode, 401); assert.equal(transactions, 0); } finally { globalThis.fetch = oldFetch; adminStoreAdapter.reset(); } }); });
test('wallet verification credits a mocked wallet transaction after validating the order', async () => { await env(async () => { const writes: any[] = []; let fetchCalls = 0; const oldFetch = globalThis.fetch; globalThis.fetch = (async (url: any) => { fetchCalls += 1; return fetchCalls === 1 ? {ok: true, json: async () => ({users: [{email: 'owner@example.test'}]})} : {ok: true, json: async () => ({amount: 20000, notes: {purchaseType: 'whatsapp_wallet', workspaceScope: 'owner'}})}; }) as any; const walletRef: any = {path: 'users/owner/whatsapp_wallet/active', get: async () => ({exists: true, data: () => ({balancePaise: 1000, totalSpentPaise: 0})})}; const ledgerRef: any = {path: 'ledger', get: async () => ({exists: false, data: () => ({})})}; const fakeDb: any = {doc: (path: string) => path.includes('whatsapp_wallet/active/ledger') ? ledgerRef : path.includes('whatsapp_wallet/active') ? walletRef : {get: async () => ({exists: true, data: () => ({tenantId: 'owner', workspaceScope: 'owner'})})}, runTransaction: async (fn: any) => fn({get: async (ref: any) => ref.get(), set: (ref: any, value: any) => writes.push({path: ref.path, value})})}; adminStoreAdapter.setDbForTests(() => fakeDb); try { const res = response(); await handler({method: 'POST', headers: {authorization: 'Bearer fake', 'x-firebase-api-key': 'fake'}, body: {workspaceScope: 'owner', razorpayOrderId: 'order-1', razorpayPaymentId: 'pay-1', razorpaySignature: signature('order-1', 'pay-1')}}, res); assert.equal(res.statusCode, 200); assert.equal(res.body.verified, true); assert.equal(res.body.balancePaise, 1000); assert.equal(writes.length, 2); assert.equal(writes[0].value.balancePaise, 21000); } finally { globalThis.fetch = oldFetch; adminStoreAdapter.reset(); } }); });
