import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import test from 'node:test';
import handler from '../api/razorpay/webhook';
import {subscriptionAdapter} from '../src/server/adapters/subscription';
import {adminStoreAdapter} from '../src/server/adapters/store';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const secret = 'test_webhook_secret';
const request = (raw: Buffer, signature: string) => ({method: 'POST', headers: {'x-razorpay-signature': signature}, async *[Symbol.asyncIterator]() { yield raw.subarray(0, Math.ceil(raw.length / 2)); yield raw.subarray(Math.ceil(raw.length / 2)); }});
const sign = (raw: Buffer) => createHmac('sha256', secret).update(raw).digest('hex');
const webhookDb = () => { const records = new Map<string, any>(); return {doc: (path: string) => ({path}), runTransaction: async (fn: any) => fn({get: async (ref: any) => ({exists: records.has(ref.path), data: () => records.get(ref.path)}), create: (ref: any, value: any) => { records.set(ref.path, value); }, set: (ref: any, value: any) => { records.set(ref.path, {...records.get(ref.path), ...value}); }})}; };

test('webhook rejects unsupported method and missing secret', async () => { const method = response(); await handler({method: 'GET'}, method); assert.equal(method.statusCode, 405); const old = process.env.RAZORPAY_WEBHOOK_SECRET; delete process.env.RAZORPAY_WEBHOOK_SECRET; const missing = response(); await handler(request(Buffer.from('{}'), ''), missing); if (old) process.env.RAZORPAY_WEBHOOK_SECRET = old; assert.equal(missing.statusCode, 503); });
test('webhook rejects invalid signatures without mutation or CRM call', async () => { const old = process.env.RAZORPAY_WEBHOOK_SECRET; process.env.RAZORPAY_WEBHOOK_SECRET = secret; let updates = 0; let fetches = 0; const oldFetch = globalThis.fetch; globalThis.fetch = (async () => { fetches += 1; throw new Error('unexpected CRM'); }) as any; subscriptionAdapter.setUpdaterForTests(async () => { updates += 1; }); try { const raw = Buffer.from('{"event":"subscription.activated"}'); const res = response(); await handler(request(raw, 'invalid'), res); assert.equal(res.statusCode, 401); assert.equal(updates, 0); assert.equal(fetches, 0); } finally { subscriptionAdapter.reset(); globalThis.fetch = oldFetch; old === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old; } });
test('webhook preserves raw bytes and updates subscription for a valid event', async () => { const old = process.env.RAZORPAY_WEBHOOK_SECRET; process.env.RAZORPAY_WEBHOOK_SECRET = secret; let update: any; adminStoreAdapter.setDbForTests(webhookDb as any); subscriptionAdapter.setUpdaterForTests(async (tenant, value) => { update = {tenant, value}; }); try { const raw = Buffer.from(JSON.stringify({id: 'evt-test', event: 'subscription.activated', payload: {subscription: {entity: {id: 'sub-test', current_end: 1800000000, notes: {tenantId: 'tenant-test'}}}}})); const res = response(); await handler(request(raw, sign(raw)), res); assert.equal(res.statusCode, 200); assert.deepEqual(res.body, {received: true}); assert.equal(update.tenant, 'tenant-test'); assert.equal(update.value.subscriptionStatus, 'active'); } finally { adminStoreAdapter.reset(); subscriptionAdapter.reset(); old === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old; } });
test('webhook forwards charged subscription invoices only through mocked CRM', async () => { const old = {secret: process.env.RAZORPAY_WEBHOOK_SECRET, endpoint: process.env.CRM_QPOS_WEBHOOK_URL, key: process.env.CRM_API_KEY, crmSecret: process.env.CRM_WEBHOOK_SECRET}; process.env.RAZORPAY_WEBHOOK_SECRET = secret; process.env.CRM_QPOS_WEBHOOK_URL = 'https://crm.test/webhook'; process.env.CRM_API_KEY = 'test-api-key'; process.env.CRM_WEBHOOK_SECRET = 'test-crm-secret'; let crmBody = ''; const oldFetch = globalThis.fetch; globalThis.fetch = (async (_url: any, init: any) => { crmBody = init.body; return {ok: true, text: async () => ''}; }) as any; adminStoreAdapter.setDbForTests(webhookDb as any); subscriptionAdapter.setUpdaterForTests(async () => {}); try { const raw = Buffer.from(JSON.stringify({id: 'evt-charge', event: 'subscription.charged', payload: {subscription: {entity: {id: 'sub-test', notes: {tenantId: 'tenant-test', ownerEmail: 'owner@example.test'}}}, payment: {entity: {id: 'pay-test', amount: 20000, currency: 'INR'}}}})); const res = response(); await handler(request(raw, sign(raw)), res); assert.equal(res.statusCode, 200); assert.match(crmBody, /pay-test/); } finally { adminStoreAdapter.reset(); subscriptionAdapter.reset(); globalThis.fetch = oldFetch; old.secret === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old.secret; old.endpoint === undefined ? delete process.env.CRM_QPOS_WEBHOOK_URL : process.env.CRM_QPOS_WEBHOOK_URL = old.endpoint; old.key === undefined ? delete process.env.CRM_API_KEY : process.env.CRM_API_KEY = old.key; old.crmSecret === undefined ? delete process.env.CRM_WEBHOOK_SECRET : process.env.CRM_WEBHOOK_SECRET = old.crmSecret; } });

test('webhook duplicate delivery does not repeat mutation or CRM forwarding', async () => {
  const old = {secret: process.env.RAZORPAY_WEBHOOK_SECRET, endpoint: process.env.CRM_QPOS_WEBHOOK_URL, key: process.env.CRM_API_KEY, crmSecret: process.env.CRM_WEBHOOK_SECRET};
  process.env.RAZORPAY_WEBHOOK_SECRET = secret; process.env.CRM_QPOS_WEBHOOK_URL = 'https://crm.test/webhook'; process.env.CRM_API_KEY = 'key'; process.env.CRM_WEBHOOK_SECRET = 'crm';
  let updates = 0; let fetches = 0; const oldFetch = globalThis.fetch; globalThis.fetch = (async () => { fetches++; return {ok: true, text: async () => ''}; }) as any;
  const db = webhookDb(); adminStoreAdapter.setDbForTests(() => db as any); subscriptionAdapter.setUpdaterForTests(async () => { updates++; });
  try { const raw = Buffer.from(JSON.stringify({id: 'evt-dup', event: 'subscription.charged', payload: {subscription: {entity: {id: 'sub', notes: {tenantId: 't', ownerEmail: 'o'}}}, payment: {entity: {id: 'p', amount: 1, currency: 'INR'}}}})); const first = response(); const second = response(); await handler(request(raw, sign(raw)), first); await handler(request(raw, sign(raw)), second); assert.equal(first.statusCode, 200); assert.deepEqual(second.body, {received: true, idempotent: true}); assert.equal(updates, 1); assert.equal(fetches, 1); }
  finally { adminStoreAdapter.reset(); subscriptionAdapter.reset(); globalThis.fetch = oldFetch; old.secret === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old.secret; old.endpoint === undefined ? delete process.env.CRM_QPOS_WEBHOOK_URL : process.env.CRM_QPOS_WEBHOOK_URL = old.endpoint; old.key === undefined ? delete process.env.CRM_API_KEY : process.env.CRM_API_KEY = old.key; old.crmSecret === undefined ? delete process.env.CRM_WEBHOOK_SECRET : process.env.CRM_WEBHOOK_SECRET = old.crmSecret; }
});

test('webhook handles malformed signed JSON without mutation', async () => { const old = process.env.RAZORPAY_WEBHOOK_SECRET; process.env.RAZORPAY_WEBHOOK_SECRET = secret; const raw = Buffer.from('{"event":'); const res = response(); await handler(request(raw, sign(raw)), res); assert.equal(res.statusCode, 400); assert.deepEqual(res.body, {error: 'Invalid webhook payload.'}); old === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old; });

test('webhook failure can be retried', async () => { const old = process.env.RAZORPAY_WEBHOOK_SECRET; process.env.RAZORPAY_WEBHOOK_SECRET = secret; let attempts = 0; const db = webhookDb(); adminStoreAdapter.setDbForTests(() => db as any); subscriptionAdapter.setUpdaterForTests(async () => { attempts++; if (attempts === 1) throw new Error('temporary'); }); try { const raw = Buffer.from(JSON.stringify({id: 'evt-retry', event: 'subscription.activated', payload: {subscription: {entity: {id: 'sub', notes: {tenantId: 't'}}}}})); const first = response(); const second = response(); await handler(request(raw, sign(raw)), first); await handler(request(raw, sign(raw)), second); assert.equal(first.statusCode, 502); assert.equal(second.statusCode, 200); assert.equal(attempts, 2); } finally { adminStoreAdapter.reset(); subscriptionAdapter.reset(); old === undefined ? delete process.env.RAZORPAY_WEBHOOK_SECRET : process.env.RAZORPAY_WEBHOOK_SECRET = old; } });
