import assert from 'node:assert/strict';
import test from 'node:test';
import handler from '../api/razorpay/create-whatsapp-wallet-order';
import {adminStoreAdapter} from '../src/server/adapters/store';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const withEnvironment = async (run: () => Promise<void>) => { const oldId = process.env.RAZORPAY_KEY_ID; const oldSecret = process.env.RAZORPAY_KEY_SECRET; process.env.RAZORPAY_KEY_ID = 'rzp_test_characterization_key'; process.env.RAZORPAY_KEY_SECRET = 'test_characterization_secret'; try { await run(); } finally { if (oldId === undefined) delete process.env.RAZORPAY_KEY_ID; else process.env.RAZORPAY_KEY_ID = oldId; if (oldSecret === undefined) delete process.env.RAZORPAY_KEY_SECRET; else process.env.RAZORPAY_KEY_SECRET = oldSecret; } };

test('wallet order rejects unsupported methods', async () => { const res = response(); await handler({method: 'GET'}, res); assert.equal(res.statusCode, 405); });
test('wallet order rejects unsupported top-up amounts before any network call', async () => { const oldFetch = globalThis.fetch; let called = false; globalThis.fetch = (async () => { called = true; throw new Error('unexpected network'); }) as any; try { const res = response(); await handler({method: 'POST', headers: {}, body: {amountPaise: 123}}, res); assert.equal(res.statusCode, 400); assert.equal(called, false); } finally { globalThis.fetch = oldFetch; } });
test('wallet order rejects missing authentication without invoking Razorpay', async () => { await withEnvironment(async () => { const oldFetch = globalThis.fetch; let calls = 0; globalThis.fetch = (async () => { calls += 1; return {ok: false, json: async () => ({})}; }) as any; try { const res = response(); await handler({method: 'POST', headers: {}, body: {workspaceScope: 'owner_example_test', amountPaise: 10000}}, res); assert.equal(res.statusCode, 401); assert.equal(calls, 0); } finally { globalThis.fetch = oldFetch; } }); });
test('wallet order authorizes the workspace and creates a mocked Razorpay order', async () => { await withEnvironment(async () => { const oldFetch = globalThis.fetch; let calls = 0; let razorpayRequest: any; globalThis.fetch = (async (url: any, init: any) => { calls += 1; if (calls === 1) return {ok: true, json: async () => ({users: [{email: 'owner@example.test'}]})}; razorpayRequest = {url: String(url), init}; return {ok: true, json: async () => ({id: 'wallet_order_characterization'})}; }) as any; const fakeDb: any = {doc: () => ({get: async () => ({exists: false, data: () => ({})})})}; adminStoreAdapter.setDbForTests(() => fakeDb); try { const res = response(); await handler({method: 'POST', headers: {authorization: 'Bearer fake-token', 'x-firebase-api-key': 'fake-api-key'}, body: {workspaceScope: 'owner_example_test', amountPaise: 20000}}, res); const outgoing = JSON.parse(razorpayRequest.init.body); assert.equal(calls, 2); assert.equal(razorpayRequest.url, 'https://api.razorpay.com/v1/orders'); assert.equal(outgoing.amount, 20000); assert.equal(outgoing.currency, 'INR'); assert.match(outgoing.receipt, /^wa_/); assert.deepEqual(outgoing.notes, {purchaseType: 'whatsapp_wallet', workspaceScope: 'owner_example_test', ownerEmail: 'owner@example.test'}); assert.equal(res.statusCode, 200); assert.deepEqual(res.body, {keyId: 'rzp_test_characterization_key', orderId: 'wallet_order_characterization', amount: 20000, currency: 'INR'}); } finally { adminStoreAdapter.reset(); globalThis.fetch = oldFetch; } }); });
