import assert from 'node:assert/strict';
import test from 'node:test';
import handler from '../api/razorpay/create-subscription';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const keys = ['RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET', 'RAZORPAY_BASIC_PLAN_ID'] as const;
const withEnvironment = async (run: () => Promise<void>) => { const old = Object.fromEntries(keys.map(key => [key, process.env[key]])); process.env.RAZORPAY_KEY_ID = 'rzp_test_characterization_key'; process.env.RAZORPAY_KEY_SECRET = 'test_characterization_secret'; process.env.RAZORPAY_BASIC_PLAN_ID = 'plan_characterization'; try { await run(); } finally { keys.forEach(key => old[key] === undefined ? delete process.env[key] : process.env[key] = old[key]); } };

test('subscription creation rejects unsupported methods', async () => { const res = response(); await handler({method: 'GET'}, res); assert.equal(res.statusCode, 405); });
test('subscription creation reports missing configuration', async () => { const old = process.env.RAZORPAY_BASIC_PLAN_ID; delete process.env.RAZORPAY_BASIC_PLAN_ID; const res = response(); await handler({method: 'POST', body: {}}, res); if (old === undefined) delete process.env.RAZORPAY_BASIC_PLAN_ID; else process.env.RAZORPAY_BASIC_PLAN_ID = old; assert.equal(res.statusCode, 503); });
test('subscription creation requires tenant and owner email', async () => { await withEnvironment(async () => { const res = response(); await handler({method: 'POST', body: {}}, res); assert.equal(res.statusCode, 400); }); });
test('subscription creation sends the current fixed contract to mocked Razorpay', async () => { await withEnvironment(async () => { const oldFetch = globalThis.fetch; let requested: any; globalThis.fetch = (async (url: any, init: any) => { requested = {url: String(url), init}; return {ok: true, text: async () => JSON.stringify({id: 'subscription_characterization'})}; }) as any; try { const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant-test', email: 'owner@example.test', name: 'Owner', storeName: 'Store'}}, res); const outgoing = JSON.parse(requested.init.body); assert.equal(requested.url, 'https://api.razorpay.com/v1/subscriptions'); assert.equal(outgoing.plan_id, 'plan_characterization'); assert.equal(outgoing.total_count, 10); assert.equal(outgoing.quantity, 1); assert.equal(outgoing.customer_notify, 1); assert.deepEqual(outgoing.notes, {tenantId: 'tenant-test', ownerEmail: 'owner@example.test', ownerName: 'Owner', storeName: 'Store', planTier: 'Basic'}); assert.equal(res.statusCode, 200); assert.deepEqual(res.body, {keyId: 'rzp_test_characterization_key', subscriptionId: 'subscription_characterization', planId: 'plan_characterization'}); } finally { globalThis.fetch = oldFetch; } }); });
test('subscription creation preserves upstream errors', async () => { await withEnvironment(async () => { const oldFetch = globalThis.fetch; globalThis.fetch = (async () => ({ok: false, status: 400, text: async () => JSON.stringify({error: {description: 'Rejected test subscription'}})})) as any; try { const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant-test', email: 'owner@example.test'}}, res); assert.equal(res.statusCode, 400); assert.deepEqual(res.body, {error: 'Rejected test subscription'}); } finally { globalThis.fetch = oldFetch; } }); });
