import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import test from 'node:test';
import handler from '../api/razorpay/verify';
import {subscriptionAdapter} from '../src/server/adapters/subscription';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const secret = 'test_razorpay_secret';
test('subscription verification rejects unsupported and incomplete requests', async () => { const method = response(); await handler({method: 'GET'}, method); assert.equal(method.statusCode, 405); const old = process.env.RAZORPAY_KEY_SECRET; process.env.RAZORPAY_KEY_SECRET = secret; const missing = response(); await handler({method: 'POST', body: {}}, missing); old === undefined ? delete process.env.RAZORPAY_KEY_SECRET : process.env.RAZORPAY_KEY_SECRET = old; assert.equal(missing.statusCode, 400); });
test('subscription verification rejects invalid signatures without updating Firebase', async () => { const old = process.env.RAZORPAY_KEY_SECRET; process.env.RAZORPAY_KEY_SECRET = secret; let updates = 0; subscriptionAdapter.setUpdaterForTests(async () => { updates += 1; }); try { const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant', razorpayPaymentId: 'pay', razorpaySubscriptionId: 'sub', razorpaySignature: 'invalid'}}, res); assert.equal(res.statusCode, 401); assert.equal(updates, 0); } finally { subscriptionAdapter.reset(); old === undefined ? delete process.env.RAZORPAY_KEY_SECRET : process.env.RAZORPAY_KEY_SECRET = old; } });
test('subscription verification activates a mocked tenant subscription', async () => { const old = process.env.RAZORPAY_KEY_SECRET; process.env.RAZORPAY_KEY_SECRET = secret; let update: any; subscriptionAdapter.setUpdaterForTests(async (tenant, value) => { update = {tenant, value}; }); try { const payment = 'pay-test'; const sub = 'sub-test'; const sig = createHmac('sha256', secret).update(`${payment}|${sub}`).digest('hex'); const res = response(); await handler({method: 'POST', body: {tenantId: 'tenant-test', razorpayPaymentId: payment, razorpaySubscriptionId: sub, razorpaySignature: sig}}, res); assert.equal(res.statusCode, 200); assert.equal(res.body.verified, true); assert.equal(update.tenant, 'tenant-test'); assert.equal(update.value.subscriptionStatus, 'active'); } finally { subscriptionAdapter.reset(); old === undefined ? delete process.env.RAZORPAY_KEY_SECRET : process.env.RAZORPAY_KEY_SECRET = old; } });
