import assert from 'node:assert/strict';
import test from 'node:test';
import handler from '../api/razorpay/create-subscription';
import {setAuthForTests, resetAuthForTests} from '../api/_online-store';

const response = () => ({statusCode: 0, body: undefined as any, status(code: number) { this.statusCode = code; return this; }, json(value: any) { this.body = value; return this; }});
const keys = ['RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET', 'RAZORPAY_BASIC_PLAN_ID'] as const;
const withEnvironment = async (run: () => Promise<void>) => { const old = Object.fromEntries(keys.map(key => [key, process.env[key]])); process.env.RAZORPAY_KEY_ID = 'rzp_test_characterization_key'; process.env.RAZORPAY_KEY_SECRET = 'test_characterization_secret'; process.env.RAZORPAY_BASIC_PLAN_ID = 'plan_characterization'; try { await run(); } finally { keys.forEach(key => old[key] === undefined ? delete process.env[key] : process.env[key] = old[key]); } };

test('subscription creation rejects unsupported methods', async () => { const res = response(); await handler({method: 'GET'}, res); assert.equal(res.statusCode, 405); });
test('subscription creation reports missing configuration', async () => { const old = process.env.RAZORPAY_BASIC_PLAN_ID; delete process.env.RAZORPAY_BASIC_PLAN_ID; const res = response(); await handler({method: 'POST', body: {}}, res); if (old === undefined) delete process.env.RAZORPAY_BASIC_PLAN_ID; else process.env.RAZORPAY_BASIC_PLAN_ID = old; assert.equal(res.statusCode, 503); });
test('subscription creation requires tenant and owner email', async () => { await withEnvironment(async () => { const res = response(); await handler({method: 'POST', body: {}}, res); assert.equal(res.statusCode, 400); }); });
test('subscription creation sends the current fixed contract to mocked Razorpay', async () => { await withEnvironment(async () => { setAuthForTests(() => ({verifyIdToken: async () => ({email:'owner@example.test', tenantId:'tenant-test', name:'Owner'})}) as any); const oldFetch = globalThis.fetch; let requested: any; globalThis.fetch = (async (url: any, init: any) => { requested = {url: String(url), init}; return {ok: true, text: async () => JSON.stringify({id: 'subscription_characterization'})}; }) as any; try { const res = response(); await handler({method: 'POST', headers:{authorization:'Bearer token'}, body: {tenantId: 'tenant-test', email: 'ignored', name: 'Owner', storeName: 'Store'}}, res); const outgoing = JSON.parse(requested.init.body); assert.equal(outgoing.plan_id, 'plan_characterization'); assert.equal(outgoing.notes.tenantId, 'tenant-test'); assert.equal(outgoing.notes.ownerEmail, 'owner@example.test'); assert.equal(res.statusCode, 200); } finally { globalThis.fetch = oldFetch; resetAuthForTests(); } }); });
test('subscription creation preserves upstream errors', async () => { await withEnvironment(async () => { setAuthForTests(() => ({verifyIdToken: async () => ({email:'owner@example.test', tenantId:'tenant-test'})}) as any); const oldFetch = globalThis.fetch; globalThis.fetch = (async () => ({ok: false, status: 400, text: async () => JSON.stringify({error: {description: 'Rejected test subscription'}})})) as any; try { const res = response(); await handler({method: 'POST', headers:{authorization:'Bearer token'}, body: {tenantId: 'tenant-test', email: 'owner@example.test'}}, res); assert.equal(res.statusCode, 400); assert.deepEqual(res.body, {error: 'Rejected test subscription'}); } finally { globalThis.fetch = oldFetch; resetAuthForTests(); } }); });
